services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.lycdbhkkexzeqammrqaw.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: Munees@2004
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Munees@n8n"
      - key: WEBHOOK_URL
        value: https://n8n-m45f.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
