services:
  - type: web
    name: n8n
    env: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-ap-northeast-2.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.lycdbhkkexzeqammrqaw
      - key: DB_POSTGRESDB_PASSWORD
        value: "Munees@2004"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: DB_POSTGRESDB_SSL
        value: "true"
      - key: N8N_LOG_LEVEL
        value: debug
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_ENCRYPTION_KEY
        value: n8n_secretroot_key_2024
      - key: WEBHOOK_URL
        value: https://n8n-m45f.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
